### ISSUE TITLE
Why delete zh-cn translation in Ver 1.0.9 ? It's working in Ver 1.0.8 correctly

### ISSUE THREAD

**Issue by Hoozava** [Khazoda/bronze#12]
If your PC cannot display Chinese characters correctly,it's normal.You are maybe need to install Chinese language package from your system language page,and use the UTF-8 format to read it.That's all right in Chinese PC.

**Comment by Khazoda** [comment]
Thank you for noticing this, I messed up - 
I built 1.0.9+1.21 from the wrong branch that didn't have the updated chinese translations in. 
This will be fixed in 1.0.10+1.21.

Sorry for the mistake!
