### ISSUE TITLE
[Feature] Allow Copper and Tin to be used as Trim materials?

### ISSUE THREAD

**Issue by Coder-Relri** [Khazoda/bronze#15]
While trying out this mod I noticed that you can't use Tin or Bronze as trim materials for armour, and I thought that's a shame since materials like Quartz and Copper are the capable of being used as trim materials. 

I've seen certain mods use the Trimmed mod as a way to make their ingots/materials be used as trim materials, so maybe you could have a soft dependency to that mod? 

Absolutely love this mod by the way, I can't wait for what else you have planned for it. ❤️

**Comment by Khazoda** [comment]
This is definitely something I want to include if possible.
Thanks for the feature request, if I do add trims for tin and bronze it'll be mentioned in this issue :)
