### ISSUE TITLE
REQUEST: Stackable on crafting table

### ISSUE THREAD

**Issue by Wytchcat** [Khazoda/bronze#17]
Please make raw bronze stackable on crafting table. 

Thanks!

**Comment by Khazoda** [comment]
Hi, do you mean bronze blend?
Could you please tell me what version of Minecraft, and what version of the mod you're running?
I'm unable to reproduce this issue:
![image](https://github.com/user-attachments/assets/f10ce92d-c53c-4ea6-a671-b03423b49c37)

**Comment by Khazoda** [comment]
I'm closing this issue due to a lack of follow-up. If you're still experiencing your problem, please open another issue.
