### ISSUE TITLE
Where do they spawn??

### ISSUE THREAD

**Issue by QueDoom** [Khazoda/bronze#21]
At what y level do they spawn?

**Comment by Khazoda** [comment]
Tin ore spawns between y levels `-12` and `96`, with it being most plentiful around `42`.

To put that in context, iron ore spawns in multiple places: 
- `-24` → `56` (main underground veins)
-  `0` → `72` (small underground veins)
- `80` → `384` (mountains)

Tin ore spawns slightly less frequently than iron ore, and only in the one range specified, meaning it's around 1.5 times more uncommon than iron ore (roughly). The best way to find it is by going caving above the deepslate layer, or by strip mining around y = `42`

As this is the second time I've received this question I'm going to add some information about spawn rates to the mod pages on Modrinth and CurseForge, so thank you for bringing it to my attention that this is info people want 😊
