### ISSUE TITLE
[1.21.1] Bronze Club & Quarterstaff not working w/ Better Combat + Basic Weapons

### ISSUE THREAD

**Issue by Lockehartt** [Khazoda/bronze#28]
Title pretty much says it, but to be more specific:

- Bronze Club does not use default Club animations, retains vanilla swing
- Bronze Quarterstaff only uses first of the 6 different hit animations

Idk if this is specifically an issue with Bronze itself or something is up with the other mods, but figured I'd report it anyhow in case it is something this mod has to fix.

**Comment by Lockehartt** [comment]
Sorry, just forgot that I already reported this on the Basic Weapons page! Just saw your response, thanks!

**Comment by Khazoda** [comment]
No worries @Lockehartt :), You did initially post the issue here but I moved it to the Basic Weapons repository as the issue was in that mod rather than this one, sorry for the confusion 😅
