### ISSUE TITLE
[FEATURE] Bronze Shield but way more durable than normal shield.

### ISSUE THREAD

**Issue by makumaku1974** [Khazoda/bronze#3]
A shield that is coated with Bronze. You still need to craft the normal shield then coating it with Bronze makes it more durable (Which is extending the shields durability).

**Comment by Khazoda** [comment]
I toyed with making a bronze shield for the mod during development, but felt it strayed from vanilla too much unfortunately. It'd be similar to making a 'bronze bow' or 'bronze crossbow', those weapons have 1 variant in vanilla, and I think it should stay that way.

That being said I am open to making some other class of armament that's made with bronze, similarly to how shields are made with iron, I just don't think it should be a direct upgrade of the shield itself.

**Comment by Khazoda** [comment]
If you have any further ideas feel free to leave another issue - thanks again for the suggestion, it's a good one, I just personally don't feel it fits in the mod that way.
