### ISSUE TITLE
Backport to 1.20.1 for Quilt?

### ISSUE THREAD

**Issue by sapphiriza** [Khazoda/bronze#5]
Hi! I was curious how much effort it would be to backport the mod to 1.20.1 on Quilt/Fabric. I'm aware there are a lot of changes between 1.20.1 and 1.20.6, but a lot of the mods I know and love still only run on 1.20.1, so I thought I'd ask just in case and voice that there's some interest in backporting _just a little bit_. No worries if you're not interested!

Cheers!

**Comment by Khazoda** [comment]
Hi, thanks for question! 1.20.1 has matured enough for me to realise it's likely going to be the main stable version for mod packs for a while.

This means that I *do* have the intention to port Bronze to 1.20.1 (as well as Basic Storage). I can't give a good timescale for this unfortunately, but it's on the agenda.

**Comment by Khazoda** [comment]
As an addendum, as you mentioned Quilt - I will build the mod for fabric and make sure it works in a quilt environment.

**Comment by Khazoda** [comment]
Bronze has been ported to a stable version on 1.20.1 Fabric/Quilt.
If you run into any quilt-specific issues, please let me know. Thanks!

https://modrinth.com/mod/bronze/version/1.0.10+1.20.1
https://www.curseforge.com/minecraft/mc-mods/bronze-mod/files/5642117
